### ISSUE TITLE
ProgressBar MinValue/MaxValue misspelling

### ISSUE THREAD

**Issue by Glooger** [lastunicorn/ConsoleTools#34]
**sources/ConsoleTools/ConsoleTools/Spinners/ProgressBar.cs**

` if (value > MaxValue)
                    throw new ArgumentOutOfRangeException(nameof(value), "MinValue cannot be grater than MaxValue.");`
and
` if (value > MinValue)
                    throw new ArgumentOutOfRangeException(nameof(value), "MaxValue cannot be less than MinValue.");`

need
` if (value < MinValue)
                    throw new ArgumentOutOfRangeException(nameof(value), "MaxValue cannot be less than MinValue.");`

**Comment by lastunicorn** [comment]
Fixed in version 0.5.1

**Comment by lastunicorn** [comment]
@Glooger - Is the ver 0.5.1 fixing your problem?
