### ISSUE TITLE
Make a .net standard release

### ISSUE THREAD

**Issue by waterfoul** [lastunicorn/ConsoleTools#38]
### Description
If you build targeting .net standard you will support .net framework and .net core in one build. See https://docs.microsoft.com/en-us/dotnet/standard/net-standard
### Version (Library version that you are using)
0.5.1

**Comment by lastunicorn** [comment]
I'll give it a try.

**Comment by lastunicorn** [comment]
I investigated your idea these days.

My intention is to target also .Net Framework 4.5.2 and .Net Standard is lacking some classes, but I found another approach.
I will recreate the ConsoleTools project in .Net Core. The new format of the csproj file is supporting multitarget. I will compile for both .Net Framework and .Net Core.

A new release will come soon.
