### ISSUE TITLE
YesNoQuestion - Make foreground color customizable

### ISSUE THREAD

**Issue by principis** [lastunicorn/ConsoleTools#41]
## Feature request
Make foreground color of the YesNoQuestion text customizable.

### Description
The default EmphasiesColor is in some environments difficult to read and it's currently impossible to change.

**Comment by lastunicorn** [comment]
I'll make a hot fix.

**Comment by lastunicorn** [comment]
I released a new version: 0.5.3

It has two new properties to set foreground and background colors for the question text.
Also, ForegroundColor and BackgroundColor properties are used now to display the rest of the control (the list of possible answers). They were not used until now in this control.

**Comment by principis** [comment]
Great, thanks! :)
