### ISSUE TITLE
Possible bug on tabular data. (Changing Colors) 

### ISSUE THREAD

**Issue by DanialBruce** [lastunicorn/ConsoleTools#42]
--------------------------------------------------

## **Bug Report**
I believe datagrid.BackgroundColor and datagrid.ForegroundColor are not working properly.

### **Steps to reproduce**

Use  datagrid.BackgroundColor and datagrid.ForegroundColor to try to change Background or Foreground color of any  dataGrid type table. It won't change. 

Note: I haven't found any documentation on how to change Table colors. I assumed that if I set values to these properties, it will change table colors.

Following is the code I tried to get it to work:

```
DataGrid dataGrid = new DataGrid("Työtekijöiden Lista");
                    dataGrid.ForegroundColor =(ConsoleColor) SetColorTo.TextColor; 
                    dataGrid.Columns.Add("Name");
                    dataGrid.Columns.Add("Age");
                    dataGrid.Columns.Add("Sallary");
                    dataGrid.Columns.Add("Gross");
                    dataGrid.DisplayBorderBetweenRows = true;
                    dataGrid.DisplayColumnHeaders = true;
                    dataGrid.BorderTemplate = BorderTemplate.PlusMinusBorderTemplate;
                    
                    dataGrid.Display();

```
              

I usually able to change Color in on Console using:

                    Console.BackgroundColor = ConsoleColor.'Color of my choice';
                    Console.Clear();

### **Actual behavior**

Nothing changes. Colors stay as White for headers and titles and borderlines and grey for the values within Columns.
### **Expected behavior**

Change table color.

**Comment by lastunicorn** [comment]
Hi DanialBruce,
I will investigate the bug and I'll come back with an answer.

**Comment by lastunicorn** [comment]
I was able to reproduce the bug. I am working on it.

**Comment by lastunicorn** [comment]
I fixed the `ForegroundColor` and `BackgroundColor` properties. I also added:
- `BorderColor`, `BorderBackgroundColor`
- `TitleColor`, `TitleBackgroundColor`
- `HeaderColor`, `HeaderBackgroundColor`

Please verify if they fulfill your needs.
Have a nice coding day :)

**Comment by DanialBruce** [comment]
I can verify it is fixed and is working flawlessly!

Thanks for your time and effort.
Have a wonderful day!
