### ISSUE TITLE
TextMenu title color is ignored

### ISSUE THREAD

**Issue by PhilipDaniels** [lastunicorn/ConsoleTools#48]
Here:

https://github.com/lastunicorn/ConsoleTools/blob/1eb42c81bb32c7d98b5b089932061dac67f821be/sources/ConsoleTools/ConsoleTools.Controls.Menus/TextMenu.cs#L193

You should be calling `public void WriteRow(ConsoleColor? foregroundColor, ConsoleColor? backgroundColor, string text)` and passing in the TitleForegroundColor and TitleBackgroundColor properties.

**Comment by lastunicorn** [comment]
I released a new version with the fix.
