### ISSUE TITLE
Suddenly the package became deprecated on nuget.org

### ISSUE THREAD

**Issue by cagianx** [lastunicorn/ConsoleTools#55]
Hi,

thanks for your work ✌️
Do you know why this is happening?  [https://www.nuget.org/packages/ConsoleTools](https://www.nuget.org/packages/ConsoleTools)

![image](https://user-images.githubusercontent.com/1827900/155951581-b7699e3b-dde4-4dac-93f7-1b7dd6212aa7.png)

**Comment by lastunicorn** [comment]
Hi,

I released a new version (the 0.6.0), but there are some problems with it and it is not usable.
My intention was to remove it, but nuget.org does not accept deleting a package, so I made it deprecated.

Please use the previous version: 0.5.5. It is stable.

PS: I just removed the 0.6.0 from the listing to not be visible anymore. It should be ok now.

**Comment by cagianx** [comment]
ok, no problem, thanks for the reply 👍
