### ISSUE TITLE
Spinner is missing Start and Stop method as specified in the example

### ISSUE THREAD

**Issue by GunSharp** [lastunicorn/ConsoleTools#69]
# Steps to reproduce
Use the example given in https://github.com/lastunicorn/ConsoleTools/wiki/Spinner#instance-more-power
However,

# Expected behavior
The start & stop method should be there..

# Versions
- 1.0.0
- Windows 10,
-  framework 4.7.2

**Comment by lastunicorn** [comment]
Hi @GunSharp ,

Thank you for the comment. Indeed, the documentation remained behind de actual code.
The `Start` and `Stop` methods have been replaced by the `Display` and `Close` provided by the `LongRunningControl` base class.

I will update the documentation.

**Comment by lastunicorn** [comment]
I updated the documentation.
